// Auto-generated by bitslice_compiler.py from a trained bitslice_life.py
// network -- do not hand-edit. One thread per 32-cell word; see
// web/compare/bitpack.wgsl for the packing/toroidal-wrap convention this
// kernel reuses (shift_west/shift_east generalize that file's west/east to
// an arbitrary shift distance, since 3x3 windows need up to
// 1-word-bit shifts).

struct Params {
    words_per_row: u32,
    height: u32,
    dispatch_x: u32,
}

@group(0) @binding(0) var<uniform> params: Params;
@group(0) @binding(1) var<storage, read> src: array<u32>;
@group(0) @binding(2) var<storage, read_write> dst: array<u32>;

fn shift_west(self_w: u32, prev_w: u32, k: u32) -> u32 {
    return (self_w << k) | (prev_w >> (32u - k));
}

fn shift_east(self_w: u32, next_w: u32, k: u32) -> u32 {
    return (self_w >> k) | (next_w << (32u - k));
}

@compute @workgroup_size(256)
fn main(@builtin(workgroup_id) wgid: vec3<u32>, @builtin(local_invocation_id) lid: vec3<u32>) {
    let wpr = params.words_per_row;
    let h = params.height;
    let total = wpr * h;
    let idx = (wgid.y * params.dispatch_x + wgid.x) * 256u + lid.x;
    if (idx >= total) { return; }
    let row = idx / wpr;
    let col = idx % wpr;
    let col_prev = (col + wpr - 1u) % wpr;
    let col_next = (col + 1u) % wpr;
    let rowm1_idx = (row + h - 1) % h;
    let rowm1_c = src[rowm1_idx * wpr + col];
    let row0_idx = (row + h + 0) % h;
    let row0_c = src[row0_idx * wpr + col];
    let row1_idx = (row + h + 1) % h;
    let row1_c = src[row1_idx * wpr + col];
    let rowm1_p = src[rowm1_idx * wpr + col_prev];
    let rowm1_n = src[rowm1_idx * wpr + col_next];
    let row0_p = src[row0_idx * wpr + col_prev];
    let row0_n = src[row0_idx * wpr + col_next];
    let row1_p = src[row1_idx * wpr + col_prev];
    let row1_n = src[row1_idx * wpr + col_next];
    let x0: u32 = shift_west(rowm1_c, rowm1_p, 1u);
    let x1: u32 = rowm1_c;
    let x2: u32 = shift_east(rowm1_c, rowm1_n, 1u);
    let x3: u32 = shift_west(row0_c, row0_p, 1u);
    let x4: u32 = row0_c;
    let x5: u32 = shift_east(row0_c, row0_n, 1u);
    let x6: u32 = shift_west(row1_c, row1_p, 1u);
    let x7: u32 = row1_c;
    let x8: u32 = shift_east(row1_c, row1_n, 1u);
    let g0: u32 = x8 ^ x7;
    let g1: u32 = g0 ^ x6;
    let g2: u32 = g1 ^ x5;
    let g3: u32 = g2 ^ x3;
    let g4: u32 = g3 ^ x2;
    let g5: u32 = g4 ^ x1;
    let g6: u32 = g5 & x0;
    let g7: u32 = g3 & x2;
    let g8: u32 = x2 & x1;
    let g9: u32 = g7 | g8;
    let g10: u32 = g3 & x1;
    let g11: u32 = g9 | g10;
    let g12: u32 = g6 ^ g11;
    let g13: u32 = g1 & x5;
    let g14: u32 = x5 & x3;
    let g15: u32 = g13 | g14;
    let g16: u32 = g1 & x3;
    let g17: u32 = g15 | g16;
    let g18: u32 = g12 ^ g17;
    let g19: u32 = x8 & x7;
    let g20: u32 = x7 & x6;
    let g21: u32 = g19 | g20;
    let g22: u32 = x8 & x6;
    let g23: u32 = g21 | g22;
    let g24: u32 = g18 & g23;
    let g25: u32 = g6 & g11;
    let g26: u32 = g11 & g17;
    let g27: u32 = g25 | g26;
    let g28: u32 = g6 & g17;
    let g29: u32 = g27 | g28;
    let g30: u32 = g24 & g29;
    let g31: u32 = ~g30;
    let g32: u32 = g24 ^ g29;
    let g33: u32 = g31 ^ g32;
    let g34: u32 = ~g33;
    let g35: u32 = x8 ^ x7;
    let g36: u32 = g35 ^ x6;
    let g37: u32 = g36 ^ x5;
    let g38: u32 = g37 ^ x4;
    let g39: u32 = g38 ^ x3;
    let g40: u32 = g39 ^ x2;
    let g41: u32 = g40 & x1;
    let g42: u32 = x1 & x0;
    let g43: u32 = g41 | g42;
    let g44: u32 = g40 & x0;
    let g45: u32 = g43 | g44;
    let g46: u32 = g38 & x3;
    let g47: u32 = x3 & x2;
    let g48: u32 = g46 | g47;
    let g49: u32 = g38 & x2;
    let g50: u32 = g48 | g49;
    let g51: u32 = g45 ^ g50;
    let g52: u32 = g36 & x5;
    let g53: u32 = x5 & x4;
    let g54: u32 = g52 | g53;
    let g55: u32 = g36 & x4;
    let g56: u32 = g54 | g55;
    let g57: u32 = g51 ^ g56;
    let g58: u32 = x8 & x7;
    let g59: u32 = x7 & x6;
    let g60: u32 = g58 | g59;
    let g61: u32 = x8 & x6;
    let g62: u32 = g60 | g61;
    let g63: u32 = g57 & g62;
    let g64: u32 = g45 & g50;
    let g65: u32 = g50 & g56;
    let g66: u32 = g64 | g65;
    let g67: u32 = g45 & g56;
    let g68: u32 = g66 | g67;
    let g69: u32 = g63 & g68;
    let g70: u32 = ~g69;
    let g71: u32 = g63 ^ g68;
    let g72: u32 = ~g71;
    let g73: u32 = g57 ^ g62;
    let g74: u32 = ~g73;
    let g75: u32 = g40 ^ x1;
    let g76: u32 = g75 ^ x0;
    let g77: u32 = ~g76;
    let g78: u32 = g74 & g77;
    let g79: u32 = g72 & g78;
    let g80: u32 = g70 ^ g79;
    let g81: u32 = g72 ^ g78;
    let g82: u32 = g74 ^ g77;
    let g83: u32 = g81 & g82;
    let g84: u32 = g80 ^ g83;
    let g85: u32 = ~g84;
    let g86: u32 = g34 & g85;
    let g87: u32 = ~g86;
    let g88: u32 = g34 ^ g85;
    let g89: u32 = ~g88;
    let g90: u32 = g87 ^ g89;
    let g91: u32 = ~g90;
    dst[row * wpr + col] = g91;
}
